### ISSUE TITLE
Way to check weather bluetooth is on

### ISSUE THREAD

**Issue by A-Walrus** [bluez-rs/bluez-async#133]
Add a way to check whether bluetooth is currently on.
Something equivalent to:
```shell
bluetoothctl show
Controller ...
...
Powered: no/yes
```
I want to be able to alert the user when they are trying to use my program without Bluetooth enabled.

**Comment by qwandor** [comment]
Have you tried `session.get_adapter_info()?.powered`?

**Comment by A-Walrus** [comment]
Oh my bad. Looked through the success and missed it. Thanks!
