### ISSUE TITLE
tokio feature 'rt' required for building

### ISSUE THREAD

**Issue by HeikoRibberink** [bluez-rs/bluez-async#15]
While building bluez-async v0.5.1, I encountered the following errors:
`error[E0432]: unresolved import 'tokio::task::JoinError'`
`error[E0425]: cannot find function 'spawn' in crate 'tokio'`

After inspecting the cargo.toml I found that in `tokio v1.0.1`, which is used by the most recent bluez-async, both the import and the function specified by the errors require the feature 'rt'. However, this function is only under the dev-dependencies for tokio, causing both errors:

`[dependencies.tokio]
version = "1.0.1"`

`[dev-dependencies.tokio]
version = "1.0.1"
features = ["macros", "rt", "rt-multi-thread", "time"]`

How to fix:
Specify 'rt' as a feature with tokio, under the normal dependencies.

(This is my first time opening an issue on GitHub, and I didn't find any guidelines for creating an issue, so please leave constructive feedback if possible.)

**Comment by qwandor** [comment]
Thanks for the bug report, and well spotted.

For some reason I can't reproduce the build error, `bluez-async` builds fine for me even without adding the `rt` feature for `tokio`, so I guess it's somehow being enabled anyway. In any case, it should be enabled explicitly so I'll fix that.

**Comment by qwandor** [comment]
I've pushed the fix to `main`, if that looks good to you then I can push a new release to crates.io.

**Comment by HeikoRibberink** [comment]
Seems good to me.

**Comment by HeikoRibberink** [comment]
> I've pushed the fix to `main`, if that looks good to you then I can push a new release to crates.io.

Can you please still do this?

**Comment by qwandor** [comment]
Thanks for the reminder, done now.

**Comment by HeikoRibberink** [comment]
It works now, thanks!
