### ISSUE TITLE
Add feature flags?

### ISSUE THREAD

**Issue by liamhays** [bluez-rs/bluez-async#229]
I'm using bluez-async through [btleplug](https://docs.rs/btleplug) and bluez-async is by far the biggest crate in my project because of all its dependencies. I recognize that some of these dependencies are absolutely necessary (`dbus`, `futures`), but I don't think that `serde` or `serde-xml-rs` are required for every use of this crate. Would it be possible to put `serde` functionality behind a feature flag so that bluez-async's dependencies can be limited as needed?

**Comment by qwandor** [comment]
Sure, please send a PR.

**Comment by liamhays** [comment]
Okay, I dug into adding `#[cfg...` flags, and it looks like `serde` is required for introspection on the D-Bus XML service declaration.

I'm closing the issue since obviously bluez-async needs to talk to D-Bus.
