### ISSUE TITLE
Add missing DeviceInfo properties

### ISSUE THREAD

**Issue by GreenDjango** [bluez-rs/bluez-async#75]
Hi,
Is there a reason why all the `OrgBluezDevice1` properties are not implemented in bluez-async DeviceInfo struct (like [class](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/device-api.txt#n157) or [icon](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/device-api.txt#n152)) ?
These properties are available in  [device1.rs](https://github.com/bluez-rs/bluez-async/blob/main/bluez-generated/src/device1.rs)

**Comment by qwandor** [comment]
Hi!
No particular reason, I just didn't have a use for them, and I don't think they were set on the devices I was testing with. Feel free to send a PR to add them if you like.
