### ISSUE TITLE
`WakeAllowed` property appears to not be mandatory

### ISSUE THREAD

**Issue by FireyFly** [bluez-rs/bluez-async#98]
Hey, I was checking out [mijia-homie][1] and running into issues setting it up--seemingly no devices are being found by the `bluez-async` scan at all (never mind whether they're the thermometers).

After some debugging, I've figured they get culled out in `DeviceInfo::from_properties`, specifically when we try to read the `WakeAllowed` field from the properties map. Looking at the devices in `gdbus` I see the property declared but without a value under devices: `readwrite b WakeAllowed;` (which is to say, it's not an ancient bluez version predating the field existing or so)

I searched around but couldn't really find any indication on whether some fields are mandatory and others optional. The network/bluetooth controller on this laptop is apparently Qualcomm QCA6390, if it somehow turns out to depend on controller hardware...

Simply changing to `device_properties.wake_allowed().unwrap_or(false)` seems to work fine (and would probably be a sensible default).

[1]: https://github.com/alsuren/mijia-homie

**Comment by qwandor** [comment]
Thanks for the bug report! I haven't seen this before. Your suggested fix seems reasonable, so I've sent a PR to do that. I'll release a new version shortly.
